name = "proxy-llms"
main = "server.ts"
compatibility_date = "2023-12-01"
 
[durable_objects]
bindings = [
  { name = "PROCESSOR", class_name = "ProcessorDurableObject" }
]
 
[[migrations]]
tag = "v1"
new_sqlite_classes = ["ProcessorDurableObject"]
 
[observability]
[observability.logs]
enabled = true
invocation_logs = true
 
[vars]
NVIDIA_BASE_URL = "https://integrate.api.nvidia.com/v1"
