name = "proxy-llms"
main = "server.ts"
compatibility_date = "2023-12-01"
 
[durable_objects]
bindings = [
  { name = "PROCESSOR", class_name = "ProcessorDurableObject" }
]
 
[[migrations]]
tag = "v1"
new_sqlite_classes = ["ProcessorDurableObject"]
 
[observability]
[observability.logs]
enabled = true
invocation_logs = true

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "request_metrics"

